More advanced job submission
In short:
- check the status code after running the executable in the job script
- if the status code was anything but zero, clean up all files properly
- the same cleanup applies to the case when the final output files was corrupted
- add ability to gather statistics about each jobs
- add ability to blacklist certain nodes if they keep failing*
- detailed logging at the job submission level
- more logging at the job level

* The assumption here is that the will fail only due to faulty node (e.g. the network drive hasn't been mounted, hence certain sourceable files or libraries are inaccessible). With this option, however, it is now possible to track down the list of nodes which appeared to be faulty. With a little bit of tweaking, it might be possible to pin down the time when the faulty node appeared in the system.

This is a risky commit since I haven't tested the solution (at least generating the necessary config files works well) because SLURM doesn't accept the jobs properly at the moment. Will commit anyways since I want to move on and debug later..

diff --git a/python/templates/jobTemplate.sh.template b/python/templates/jobTemplate.sh.template
--- a/python/templates/jobTemplate.sh.template
+++ b/python/templates/jobTemplate.sh.template
@@ -2,10 +2,28 @@
 
 set -v
 
+cleanup ()
+{
+  echo -e "\n\nCleaning up"
+  rm -rf $(dirname {{ inFileNameScratch }})
+  rm -rf $(dirname {{ outFileNameScratch }})
+}
+
 echo -n "Current time: "
 date
 echo -n "Hostname: "
 hostname
+echo "Current PID:      $SLURM_TASK_PID"
+echo "Current job ID:   $SLURM_JOB_ID"
+echo "Current parition: $SLURM_JOB_PARTITION"
+
+echo -e "\n\nTesting if the network drive is mounted"
+MOUNT_POINT="/cvmfs/cms.cern.ch"
+MOUNT_TEST=$(cat /proc/mounts | grep $MOUNT_POINT | awk '{print $4}')
+if [ -z $MOUNT_TEST ]; then
+  echo -e "\n\nCannot access $MOUNT_POINT\nBailing out";
+  exit 1;
+fi
 
 echo -e "\n\nInitializing CMSSW run-time environment"
 
@@ -30,10 +48,17 @@ echo "{{ execName }} {{ pythonCfg }}"
 LINE=$(seq -s= 30|tr -d '[:digit:]')
 echo "${LINE} BEGIN ${LINE}"
 {{ execName }} {{ pythonCfg }}
+RET_CODE=$?
 echo "${LINE}= END =${LINE}"
 
 echo -n -e "\n\nFinished at "
 date
+
+if [ $RET_CODE -ne 0 ]; then
+  echo "\n\nThe program did not finish successfully ($RET_CODE)";
+  cleanup
+  exit $RET_CODE;
+fi
 
 echo -e "\n\nCreating directory $(dirname {{ outFileNameLocal }})"
 mkdir -p $(dirname {{ outFileNameLocal }})
@@ -41,8 +66,18 @@ mkdir -p $(dirname {{ outFileNameLocal }})
 echo -e "\n\nMoving {{ outFileNameScratch }} to {{ outFileNameLocal }}"
 mv {{ outFileNameScratch }} {{ outFileNameLocal }}
 
-echo -e "\n\nCleaning up"
-rm -rf $(dirname {{ inFileNameScratch }})
+cleanup
+
+ZOMBIE_MACRO="{{ zombieMacro }}"
+if [ -z $ZOMBIE_MACRO ] && [ -f $ZOMBIE_MACRO ]; then
+  echo -e "\n\nTesting if the file {{ outFileNameLocal }} is corrupted"
+  root -b -l -q "$ZOMBIE_MACRO(\"{{ outFileNameLocal }}\")"
+  TEST_IF_ZOMBIE=$?
+  if [ $TEST_IF_ZOMBIE -ne 0 ]; then
+    echo "\n\nFile {{ outFileNameLocal }} is a zombie; deleting it";
+    rm -f {{ outFileNameLocal }};
+  fi
+fi
 
 echo -e "\n\nDone"
 
